spring.application.name=TrainoBook

# MySQL データベース接続設定
spring.datasource.url=jdbc:mysql://localhost:3306/traino_book
spring.datasource.username=book_user
spring.datasource.password=book_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate 設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
